version: 2

sources:
  - name: staging
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
      - name: orders
      - name: nation
      - name: part
      - name: lineitem
      - name: partsupp
      - name: region
      - name: supplier
      