with auditor as(
    select * from {{source('staging','F_STORE_AUDITOR')}}
)

select STORE_AUDIT_CD,
STORE_AUDIT_DS,
RECORD_TYPE_CD,
COUNTRY_CD,
STORE_AUDIT_DT,
ACCOUNT_CD,
VISIT_CD,
STATUS_DS,
ACCOUNT_RECORD_TYPE_DS,
STORE_AUDIT_ITEM_CD,
PRODUCT_CD,
STORE_AUDIT_REGULAR_PRICE_NM,
INDICATOR_DS,
PLAN_FL,
TEMPLATE_CD,
COMPLIANCE_LISTING_FL
from auditor
